# Generated by Django 4.2.5 on 2023-09-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getDoctors", "0002_alter_doctor_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="doctor",
            table="doctor_list",
        ),
    ]
